{% set name = "dlux" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dLux-{{ version }}.tar.gz
  sha256: 6ec47ff19d5b3cbc9d9d592ae2627f8a446f08ce5c58c1de28ae45fe628748ee

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - jax
    - jaxlib
    - zodiax >=0.4.1

test:
  imports:
    - dLux
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://louisdesdoigts.github.io/dLux/
  summary: Differentiable Optical Models as Parameterised Neural Networks in Jax using Zodiax.
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - LouisDesdoigts
    - christhechris
